vinitshahdeo/Hacktoberfest2021

MENTORS.md
=> add me as a mentor

MENTORS.md
Would like to volunteer for Hacktoberfest 2021
=> docs(New mentor): Ashwin Hariharan

MENTORS.md
Hi, I would like to volunteer myself as a mentor for the upcoming Hacktoberfest 2021.
=> Request to add Narasimha Prasanna HN (myself) as mentor

MENTORS.md
=> Added mohsin as mentor

MENTORS.md
- Name: **Gauransh Kumar**
- LinkedIn: [https://www.linkedin.com/in/gauranshk21](https://www.linkedin.com/in/gauranshk21)
- Twitter: [https://twitter.com/gauransh_k](https://twitter.com/gauransh_k)
- About: **DevOps Lead @ GDSC MAIT, Certified Kubernetes Application Developer**
=> Added Gauransh Kumar(myself) as a mentor

MENTORS.md
**Provide your information**
- Name: **Prathamesh Borse**
- LinkedIn: https://www.linkedin.com/in/prathameshborse
- Twitter: https://twitter.com/Dev_Prathamtwt
- About: **Maintainer of [@Talkslab](https://github.com/TalksLab), [Contribute-To-This-Project](https://github.com/Syknapse/Contribute-To-This-Project)**
=> Added prathameshborse as mentor

MENTORS.md
=> Adding myself as a Mentor

MENTORS.md
Mentor-Info : Update `MENTORS.md`
=> Mentor-Info : Update MENTORS.md

MENTORS.md
- Name: Aniket Bhattacharyea
- LinkedIn: https://linkedin.com/in/heraldofsolace
- Twitter: https://twitter.com/heraldofsolace
- About: I am a coder and mathematician. I work as a content writer at Draft.Dev and I specialize in Full-stack web development.
I wish to become the guide I wish I had when I started my open source journey
=> Add Aniket Bhattacharyea to mentors

MENTORS.md
I would love to be a part of this amazing program ✨✨
=> Add Saloni Subedi to MENTORS

README.md
https://github.com/dry-python/classes/issues/307
=> Adds `dry-python/classes` to the list

MENTORS.md
Hello, I'm Rahul Gulia, CV intern at Wobot.ai, would love to participate as a mentor.
=> Mentor list updated

explore/ISSUES.md
- Issue [Fix Linting](https://github.com/felixfaisal/attack-on-web/issues/31)
- Repository [Attack on web](https://github.com/felixfaisal/attack-on-web)
- Tech stack `JavaScript` `NodeJs`
=> Added beginner friendly issue 

README.md, explore/ISSUES.md
- Issue [Use Docker Volumes instead of Copy](https://github.com/felixfaisal/formica/issues/55)
- Repository [Formica](https://github.com/felixfaisal/formica)
- Tech stack `Docker`
=> New Beginner Friendly Issue

README.md
| EXPLORE  | CONNECT | BLOG POSTS  | MEDIA ASSETS  |
|---|---|---|---|
| [`ISSUES.md`](./explore/ISSUES.md)  | Mentors  | [A curated list of beginner-friendly issues for Hacktoberfest 2021](https://vinitshahdeo.dev/beginner-friendly-issues-for-hacktoberfest-2021)  | [POSTERS](./assets/posters/mentors)  |
| [`PROJECTS.md`](./explore/PROJECTS.md)  | Mentees  | [Muddle through Hacktoberfest 2021 like a Pro](https://vinitshahdeo.dev/hacktoberfest-2021) 🎉  |  [PPTs](./deck)  |
| [`EVENTS.md`](./explore/PROJECTS.md) | Admin  | [Introduction to Git & Github. Create your first PR.](https://thisisamank.me/git-intro-hacktoberfest-2021)  | [MENTOR PICTURES](./assets/pictures)  |
=> Added Quick Links

MENTORS.md
- Name: Abhishek Agrawal
- LinkedIn: https://www.linkedin.com/in/abhishekagrawal1929/
- Twitter: https://twitter.com/fazer1929
- About: A senior-year Computer Science undergrad, A Full-stack developer
=> Added myself as a mentor

explore/ISSUES.md
I want to add an issue for my project in ISSUES.md
=> add : issue for Heel2Toe

explore/ISSUES.md
Added a beginner friendly good first issue
=> Added a beginner friendly issue

MENTORS.md
=> Added Myself [ Rohan Kulkarni ] As Mentor

explore/ISSUES.md
Added a beginner level good first issue to issues.md
=> Updated issues.md

explore/ISSUES.md
Added new issue from a repository containing various programming language codes. [Issues](https://github.com/Astrodevil/Programming-Basics/issues)
=> Added new issue 

explore/ISSUES.md
In this task a name card has to be created with just basic html which when merged will be shown on [Project website](https://syknapse.github.io/Contribute-To-This-Project/).
=> Added A Basic Task Of Creating Name Card With Basic Html

MENTORS.md
- Name: <Add your name here>SUKHJIT SINGH
- LinkedIn: <Add link to your Linkedin profile>https://www.linkedin.com/in/sukhjit-singh-6a35931b5/
- Twitter: <Add link to your Twitter profile>https://twitter.com/SUKHJIT41040858
- About: <Short bio about you> GWOC'21<Contributor>💻 , HackThisFall Evengelist🙆‍♂️ , Udacity AWS ML Scholar
=> Added My Info In Mentors List

MENTORS.md
Added my name and info to the mentor's list
=> Added my name to MENTORS.md

MENTORS.md
Name : Agamjot Singh
Linkedin : https://www.linkedin.com/in/agamjot-singh
Twitter : https://twitter.com/Agamjot_Singh18
About : MERN Stack Developer, Founder @CodeSetGo
=> Added Info to Mentors List

MENTORS.md
- Name : Drishti Peshwani
- LinkedIn : https://www.linkedin.com/in/drishti-peshwani
- Twitter : https://twitter.com/Drishti0901
- About :  Hi, I am Drishti. I am a third-year undergrad student at IIT Madras. I have a great zeal for programming, and I am always excited about solving challenges and working on real-world problems. Likewise, I am skilled with C++, Python, and JavaScript and have worked with various tech frameworks. I am a self-dedicated person and always excited to learn and explore new things. Apart from this, I love to dance and read books, they are a great tool for refreshing my mind.
Mentorship has helped me a lot in my tech journey. I understand that the tech space can sometimes be really overwhelming in the beginning, I have also been through the same space and been …
=> Updated MENTORS.md

MENTORS.md
My name is not listed in the mentor, So I add my name in the list.
=> Add Sumit Singh as a Mentor

explore/ISSUES.md
Issue(s):
1. [Add hover effect to reset button](https://github.com/hardeepnarang10/keyboard-pro/issues/1)
2. [Map event listeners to trigger state change](https://github.com/hardeepnarang10/keyboard-pro/issues/2)
Repository:
[hardeepnarang10/keyboard-pro](https://github.com/hardeepnarang10/keyboard-pro)
Tech stack:
Issue #1: CSS
Issue #2: JavaScript
Yes.
=> Add Issues to ISSUES.md

explore/ISSUES.md
Issue's - https://github.com/vishal-codes/react-widgets/issues/1 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; https://github.com/vishal-codes/react-widgets/issues/3
Repository - https://github.com/vishal-codes/react-widgets
Tech Stack - Javascript, React.js, CSS,
=> Added issues in ISSUES.md file

explore/ISSUES.md
Added an issue for my [Heel2Toe](https://github.com/saloni-15/Heel2Toe) project.
=> add : issue for my project

explore/ISSUES.md
The link of the issue no 83 in ISSUES.md is been updated no
=> Updated the link of issue no 83

MENTORS.md
- **Name:** Gary Hilares
- **Twitter:** [@GaryNLOL](https://twitch.tv/garynlol)
- **About:** Hi everyone! My name is Gary and I'm from Peru 🇵🇪 . I'm happy when I get lots of new experiences, learned new things and connected with amazing people! I usually work with Python, HTML5/CSS3 /Javascript , React  and C++, which is probably my favorite language as it is the one I started with. However, I also have some experience with Java and SML. Apart from coding, I love playing chess ♟️, listening to music 🎵 , writing stories ✍️ and helping others (sometimes forcing them 🙃) to strive to improve 😋 . If you want help with anything or you just want to talk, you can contact me! 👍
=> Add new mentor.
